version: '3.8'
services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fast_foodiy
      - PERSISTENCE_DRIVER=postgres
      - PORT=3000
    depends_on:
      - db
    volumes:
      - ../src:/app/src

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: fast_foodiy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: